### PR TITLE
Add Windows and OSX to CI

### PR DESCRIPTION
**Pull request by ahojukka5**

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187

https://github.com/ararslan/Jackknife.jl/blob/master/.travis.yml

Why it's failing?

**Comment by ahojukka5** [comment]
image

https://travis-ci.org/JuliaFEM/FEMQuad.jl/jobs/591885180

"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself. Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received"

Maybe something wrong with the nightly Windows image. 

cc: @staticfloat.

**Comment by TeroFrondelius** [comment]
Can we allow nightly to fail, like this: https://github.com/JuliaFEM/MFrontInterface.jl/blob/622d708b34f4e46863f4aad635aecdb16ef34208/.travis.yml#L9-L11

**Comment by ahojukka5** [comment]
Interesting topic. Do we want to allow the failure of a nightly build for reasons not depending on the package?

**Comment by TeroFrondelius** [comment]
Nightly build = master = breaking changes. Especially when Julia will move closer to the v2.0.0 more breaking changes will be introduced to the master branch. 

My opinion we shouldn't even test with the nightly but at least minimum we should allow failures.

**Comment by ahojukka5** [comment]
Maybe now?

**Pull request merged**
