### PR TITLE
consolidate some of the standard Gauss-Legendre rules a bit

### PR DESCRIPTION
**Pull request by KristofferC**
This removes a bit of the repetition when generating the Gauss-Legendre rules. It also moves all the generation of the quadrature rules to compile time while for some cases this previously was done every time `get_rule` was called. Also, the coordinates and weights are computed programmatically which reduces the risk of typos.

I think I uncovered a bug where the name of the `GLHEX` was not correct for order 4 and 5.

It also didn't seem like `test_glquad.jl` was ever run previously.

I didn't understand why there are three implementations of `integrate` with the same function body.

### CODE REVIEW

**Review by ahojukka5 — APPROVED** [review]
Good changes. There are some systematic ways also to construct quadrature rules for triangles and tetrahedrons, but I'm not familiar with those.

**Comment by ahojukka5** [comment]
I don't recall what was the idea of having the same function with different names. We clearly should have only one implementation if the code is same. What about if we define only one `integrate` and then `global const integrate_1d = integrate` and so on.

**Comment by KristofferC** [comment]
Yeah, generating rules on triangles is harder.

Regarding `integrate`, one way to do it is to consolidate the functions into `integrate` and have a `@deprecate integrate_1d integrate` etc and then at some point in the future remove the `integrate_1d`... versions.

**Comment by KristofferC** [comment]
I think the way things are stored is a little bit awkward.

Defining a quadrature rule in `N` dimensions as something like

```
struct QuadratureRule{N}
    coords::Vector{NTuple{N, Float64}}
    weights::Vector{Float64}
end
```

seems pretty ok to me. Right now, a quadrature rule is defined as a `zip` of two vectors etc are just Julia types so it is hard to make any non-breaking changes to this.

**Comment by KristofferC** [comment]
Hmm, for dim 1 quadrature rules it seems that previously a number was used for the coordinate. 

This means that special cases like https://github.com/JuliaFEM/FEMBase.jl/blob/d96a0d39ac6978d61204b18fc8844c3e73901f84/src/elements.jl#L377-L379 and https://github.com/JuliaFEM/FEMBase.jl/blob/d96a0d39ac6978d61204b18fc8844c3e73901f84/src/elements.jl#L391-L393 has to be done.

I think using a length 1 tuple is the correct thing to do.

**Comment by ahojukka5** [comment]
LGTM, let's merge this and tag right away so that we can continue our work with FEMBase.jl.

**Pull request merged**
